definitions:
  request.CreateTodoReq:
    properties:
      name:
        type: string
    type: object
  request.UpdateTodoReq:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  termsOfService: http://swagger.io/terms/
  title: Go Boilerplate
  version: 1.0.4
paths:
  /api/v1/todos:
    get:
      consumes:
      - application/json
      description: Fetch Todo
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Fetch Todo
      tags:
      - Todos
    post:
      consumes:
      - application/json
      description: Create Todo
      parameters:
      - description: Todo to create
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/request.CreateTodoReq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create Todo
      tags:
      - Todos
  /api/v1/todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Todo
      parameters:
      - description: todo id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete Todo
      tags:
      - Todos
    get:
      consumes:
      - application/json
      description: Get Todo
      parameters:
      - description: todo id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Get Todo
      tags:
      - Todos
    put:
      consumes:
      - application/json
      description: Update Todo
      parameters:
      - description: todo id
        in: path
        name: id
        required: true
        type: string
      - description: Todo to update
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTodoReq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Update Todo
      tags:
      - Todos
swagger: "2.0"
